package:
    type:           yii2-extension
    name:           yii2-higrid
    title:          Advanced Grid for Yii2
    headline:       Yii2 HiGrid
    keywords:       grid, data tables, extension, yii2
    description:    'Grid DetailView: use grid columns for DetailView and more later'

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
